name: CI

on:
  push:
    branches:
      - main
      - ci
      - 'dev/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings

  docs:
    name: doc build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "-D warnings --html-in-header katex-header.html"

  #
  # Main test matrix
  #

  test:
    name: test (${{ matrix.os }}, ${{ matrix.rust }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, beta]
        include:
          - os: ubuntu-latest
            rust: "1.93.0"
          - os: ubuntu-latest
            rust: nightly
    continue-on-error: ${{ matrix.rust == 'nightly' || matrix.rust == 'beta' }}
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.rust }}

      - name: Build (debug)
        run: cargo build --all-features --verbose

      - name: Build (release)
        run: cargo build --release --all-features --verbose

      - name: Test (debug)
        run: cargo test --all-features --verbose

      - name: Test (release)
        run: cargo test --release --all-features --verbose

      - name: Doc tests
        run: cargo test --doc --all-features
